# -*- coding: utf-8 -*-
"""ViT_ArchictureProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CQxu03dkZryroelpSi0tMuttXshabyI4

## Setup
"""

import torch
import torchvision
import torch
import os
import matplotlib.pyplot as plt
from torchvision import datasets, transforms
from  torch.utils.data import DataLoader
from torch import nn
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

"""## Data

### transfrom
"""

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Resize((224, 224))
])

"""### Split the data into train and test datasets"""

train_data = torchvision.datasets.CIFAR10(root='data',
                                         train=True,
                                         transform=transform,
                                         download =True
                                         )
test_data = torchvision.datasets.CIFAR10(root='data',
                                         train=False,
                                         transform=transform,
                                         download=False)

"""### Creating DataLoaders"""

BATCH_SIZE = 16
train_dataloader = torch.utils.data.DataLoader(dataset=train_data,
                                               batch_size=BATCH_SIZE,
                                               shuffle = True,
                                               num_workers= os.cpu_count())
test_dataloader = torch.utils.data.DataLoader(dataset=test_data,
                                              batch_size=BATCH_SIZE,
                                              shuffle=False,
                                              num_workers= os.cpu_count()
                                              )

image, label = next(iter(train_dataloader))
image.shape, label.shape

"""## Eq. 1

* Splits the image into 16×16 patches with a strided Conv2d, prepends a learnable class token, and adds learnable position embeddings

### Patch Embedding CLass
"""

class PatchEmbedding(nn.Module):
  def __init__(self,in_channels=3,patch_size=16, embedding_dim=768,batch_size=32):
    super().__init__()

    self.first_layer = nn.Conv2d(
        in_channels=in_channels,
        out_channels =embedding_dim,
        kernel_size =patch_size,
        stride =patch_size
    )

    self.flatten = nn.Flatten(start_dim=2,
                                   end_dim=3)

    self.class_token = nn.Parameter(torch.ones(1,1,embedding_dim),
                                    requires_grad=True)
    num_patches = (224 // patch_size) ** 2
    self.positional_embedding = nn.Parameter(torch.ones(1,num_patches+1,embedding_dim),
                                             requires_grad=True)

  def forward(self,x):
    batch_size = x.shape[0]
    x = self.first_layer(x)
    x = self.flatten(x)
    x = x.permute(0, 2, 1)
    class_token = self.class_token.expand(batch_size, -1, -1)
    x_class_token= torch.cat((class_token, x),dim=1)
    positional_embedding = self.positional_embedding +x_class_token

    return positional_embedding

model= PatchEmbedding()
model(image).shape

"""## 	Eq. 2

* LayerNorm → Multi-Head Self-Attention, with a residual connection

### MSA block
"""

class MSABlock(nn.Module):
  def __init__(self,embedding_dim=768,num_heads=12):
    super().__init__()

    self.norm= nn.LayerNorm(normalized_shape=embedding_dim)
    self.msa= nn.MultiheadAttention(embed_dim=embedding_dim,num_heads=num_heads, batch_first =True)

  def forward(self,x):

        x = self.norm(x)

        out, _ = self.msa(x, x, x)

        return out

y = model(image)
model_1=MSABlock()
model_1(y).shape

"""##	Eq. 3

*	LayerNorm → MLP (Linear → GELU → Linear), with a residual connection

### MLP
"""

class MLPBlock(nn.Module):
  def __init__(self,embedding_dim=768, mlp_size=3072, dropout=0.1):
    super().__init__()
    # Layer Norm
    self.layer_norm = nn.LayerNorm(normalized_shape=embedding_dim)
    self.mlp = nn.Sequential(
      nn.Linear(in_features=embedding_dim, out_features=mlp_size),   # 768 → 3072
      nn.GELU(),
      nn.Dropout(p=dropout),
      nn.Linear(in_features=mlp_size, out_features=embedding_dim),   # 3072 → 768
      nn.Dropout(p=dropout)
  )

  def forward(self, x):
     return self.mlp(self.layer_norm(x))

model_2 =MLPBlock()
z = model_2(y)
z.shape

"""## 	Eq. 2 + 3

* Stacks the MSA and MLP blocks ×12

###TransformerEncoderBlock
"""

class TransformerEncoderBlock(nn.Module):
  def __init__(self):
    super().__init__()

    self.msa_block= MSABlock()
    self.mlp_block = MLPBlock()

  def forward(self, x):
    ## apply MSA and add residual connections
    x = self.msa_block(x) +x
    ## apply MPL and add residual connections
    x =  self.mlp_block(x) + x
    return x

Encoder =TransformerEncoderBlock()
Encoder(y).shape

"""## Eq. 4

* LayerNorm → Linear, reading from the class token

### ViT Class
"""

class ViT(nn.Module):
  def __init__(self):
    super().__init__()

    self.patch_embedding = PatchEmbedding()

    self.transformer_encoder = nn.Sequential(
       *[TransformerEncoderBlock() for _ in range(12)]
       )

    self.classifier = nn.Sequential(
        nn.LayerNorm(normalized_shape=768),
        nn.Linear(in_features=768, out_features=10)

    )

  def forward(self,x):
    x= self.patch_embedding (x)
    x= self.transformer_encoder(x)
    x= self.classifier(x[:, 0])
    return x

vit = ViT()
vit(image).shape

sum(p.numel() for p in vit.parameters())

"""## Save the Model"""

import os
os.makedirs("models", exist_ok=True)

torch.save(model.state_dict(), "models/vit.pth")

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(params=vit.parameters(), lr =1e-3, betas=(0.9, 0.999),weight_decay=0.3)
results = {}

"""## Train and test"""

def train_and_test(model, name, epochs=None, lr=0.001):
    model.to(device)
    optimizer = torch.optim.Adam(
        filter(lambda p: p.requires_grad, model.parameters()), lr=lr
    )

    # Training
    for epoch in range(epochs):
        model.train()
        running_loss = 0
        for imgs, labels in train_dataloader:
            imgs, labels = imgs.to(device), labels.to(device)
            optimizer.zero_grad()
            loss = loss_fn(model(imgs), labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
        print(f"{name} | Epoch {epoch+1}/{epochs} | Loss: {running_loss/len(train_dataloader):.4f}")

    # Testing
    model.eval()
    correct, total, test_loss = 0, 0, 0
    with torch.no_grad():
        for imgs, labels in test_dataloader:
            imgs, labels = imgs.to(device), labels.to(device)
            preds = model(imgs)
            test_loss += loss_fn(preds, labels).item()
            correct += (preds.argmax(1) == labels).sum().item()
            total += len(labels)

    acc = correct / total
    avg_loss = test_loss / len(test_dataloader)
    results[name] = {"accuracy": acc, "loss": avg_loss}
    print(f" {name} | Accuracy: {acc:.2%} | Loss: {avg_loss:.4f}\n")

    # Save and clean up
    save_path = f"/content/drive/MyDrive/{name}.pth"
    torch.save(model.state_dict(), save_path)
    print(f" Saved to {save_path}")
    del model
    torch.cuda.empty_cache()

vit_1 = train_and_test(model=vit,name='vit', epochs=5, lr=0.001)